### ISSUE TITLE
syntax error while writing email

### ISSUE THREAD

**Issue by nadal28** [monzo94/autorenueva-milanuncios#1]
![1](https://user-images.githubusercontent.com/9332807/34987608-06b8dad4-fabc-11e7-8f25-c0c9074d3c8a.PNG)

**Comment by dmonzonis** [comment]
Hola. El script está escrito en Python 3.6 (tal vez debería ponerlo en el README), y lo estás ejecutando con Python 2.7 o anterior. Instala Python 3.6 (si no lo tienes ya) e intenta ejecutar el script usando el comando `python3`.

Hazme saber si eso resuelve el problema!
