### ISSUE TITLE
elemento  no encontrado

### ISSUE THREAD

**Issue by bravelord** [monzo94/autorenueva-milanuncios#2]
buenas al ejecutarlo me indica que no encuentra el elemento lren , el cual sí existe en la pagina... 

Te ha ocurrido este error?

**Comment by dmonzonis** [comment]
Pues la verdad es que nunca me ha ocurrido. Podrías ejecutar el script con la opción `--head` activada, para ver si se llega a abrir el pop-up de renovar el anuncio? También ayudaría que pusieras todo el output del programa, incluyendo el error.

**Comment by bravelord** [comment]
Ha saltado el captcha de verificacion que piensa que es un robot, normal que no encuentre el id.

**Comment by bravelord** [comment]
ya está solucionado

**Comment by dmonzonis** [comment]
Vale, eso puede pasar a veces... Si le metes el captcha con la opción `--head` ya debería funcionar sin problema las siguientes veces. Me alegro de que lo hayas podido resolver.
